# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "graph"
title = "Isaac_Generic_MagSensor"
description = "a custom magnetometer sensor for isaacsim"
authors = ["labeeb"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/hemker.jpg"
icon = "data/hemker.jpg"

[[python.module]]
name = "isaac.generic.mag_sensor"

[dependencies]
"omni.graph.core" = {}
"omni.graph.tools" = {}

[[native.plugin]]
path = "bin/*.plugin"

[settings]
exts."isaac.generic.mag_sensor".timeout = 5